### ISSUE TITLE
Crash during restore

### ISSUE THREAD

**Issue by jreeseue** [jay0lee/got-your-back#108]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. `python3 gyb.py --email user0@gmail.com --action restore --local-folder GYB-GMail-Backup-user1\@gmail.com/`

Expected outcome (what are you trying to do?):
Restoring backup from user1 to user0 -- cloning old email address to new email address.

Actual outcome (what errors or bad behavior do you see instead?):
```
Using backup folder GYB-GMail-Backup-jreeseue@gmail.com/
restoring 10 messages (483/23870)                                               
Temp error backendError. Backing off 16 seconds...attempt 5/10

Temp error backendError. Backing off 32 seconds...attempt 6/10

Temp error backendError. Backing off 60 seconds...attempt 7/10

Temp error backendError. Backing off 60 seconds...attempt 8/10

Temp error backendError. Backing off 60 seconds...attempt 9/10
restoring 10 messages (493/23870)                                               
Temp error backendError. Backing off 16 seconds...attempt 5/10

Temp error backendError. Backing off 32 seconds...attempt 6/10

Temp error backendError. Backing off 60 seconds...attempt 7/10

ERROR: 400: BadAttachment. Skipping message restore, you can retry later with --fast-restore
restoring 10 messages (21975/23870)                                             
ERROR: 400: Invalid From header. Skipping message restore, you can retry later with --fast-restore
restoring 10 messages (22045/23870)                                             
ERROR: 400: Invalid From header. Skipping message restore, you can retry later with --fast-restore
restoring 10 messages (22055/23870)                                             
ERROR: 400: Invalid From header. Skipping message restore, you can retry later with --fast-restore
restoring 10 messages (22075/23870)                                             
ERROR: 400: Invalid From header. Skipping message restore, you can retry later with --fast-restore
restoring 10 messages (22176/23870)                                             
ERROR: 400: Invalid From header. Skipping message restore, you can retry later with --fast-restore
restoring 10 messages (22556/23870)                                             
ERROR: 400: Invalid From header. Skipping message restore, you can retry later with --fast-restore
Traceback (most recent call last):)                                             
  File "gyb.py", line 1503, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 1121, in main
    callGAPI(gbatch, None, soft_errors=True)
  File "gyb.py", line 460, in callGAPI
    return method.execute()
  File "/Users/jreese/Downloads/got-your-back-master/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/jreese/Downloads/got-your-back-master/googleapiclient/http.py", line 1397, in execute
    self._execute(http, self._order, self._requests)
  File "/Users/jreese/Downloads/got-your-back-master/googleapiclient/http.py", line 1337, in _execute
    headers=headers)
  File "/Users/jreese/Downloads/got-your-back-master/oauth2client/client.py", line 631, in new_request
    redirections, connection_type)
  File "/Users/jreese/Downloads/got-your-back-master/httplib2/__init__.py", line 1314, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/jreese/Downloads/got-your-back-master/httplib2/__init__.py", line 1064, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/jreese/Downloads/got-your-back-master/httplib2/__init__.py", line 988, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 885, in send
    self.sock.sendall(data)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 886, in sendall
    v = self.send(data[count:])
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 856, in send
    return self._sslobj.write(data)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 581, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by meeuw** [comment]
I've had the same error but now it seems to be restoring (according to the documentation you can restart a restore) now it seems to be fixed, the restore is now running for almost a day.

**Comment by jay0lee** [comment]
This error indicates a loss of Internet connectivity.

**Comment by meeuw** [comment]
Hmm might be "a loss of Internet connectivity" but would it be possible for gyb to handle this? Maybe some retries? My Internet connection is quite reliable and I don't think the outage is longer then a few seconds.
