### ISSUE TITLE
ValueError: invalid literal for int() with base 16:b''

### ISSUE THREAD

**Issue by Smadarl** [jay0lee/got-your-back#113]
I'm backing up about 100 email addresses.  This problem has only happened on two of them so far, so I don't know if it's strictly reproducible.  But maybe with the trace it will be easy to figure out what went wrong:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/http/client.py", line 541, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/local/lib/python3.5/http/client.py", line 508, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/http/client.py", line 558, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/local/lib/python3.5/http/client.py", line 543, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gyb.py", line 1580, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 1044, in main
    callGAPI(gbatch, None, soft_errors=True)
  File "gyb.py", line 487, in callGAPI
    return method.execute()
  File "/opt/got-your-back-1.0/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(_args, *_kwargs)
  File "/opt/got-your-back-1.0/googleapiclient/http.py", line 1397, in execute
    self._execute(http, self._order, self._requests)
  File "/opt/got-your-back-1.0/googleapiclient/http.py", line 1337, in _execute
    headers=headers)
  File "/opt/got-your-back-1.0/oauth2client/transport.py", line 169, in new_request
    redirections, connection_type)
  File "/opt/got-your-back-1.0/httplib2/__init__.py", line 1314, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/opt/got-your-back-1.0/httplib2/__init__.py", line 1064, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/opt/got-your-back-1.0/httplib2/__init__.py", line 1046, in _conn_request
    content = response.read()
  File "/usr/local/lib/python3.5/http/client.py", line 455, in read
    return self._readall_chunked()
  File "/usr/local/lib/python3.5/http/client.py", line 565, in _readall_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(64768 bytes read)

**Comment by supyoung** [comment]
I have the same problem, hope for resolution.

**Comment by Leustad** [comment]
It's randomly happening to me while making a GET request(same URL every time) with Python requests module.

**Comment by b0ustiflex** [comment]
I have the same issue @Smadarl. Were you able to resolve it or find a workaround ?
