### ISSUE TITLE
PyInstaller doesn't yet support Python 3.6

### ISSUE THREAD

**Issue by adamci** [jay0lee/got-your-back#129]
I'm trying to build master from the `macos-build.sh` script. I'm on a mid-2012 MBP running OSX 10.11.6.

The build seems to work until it reaches the `Analyzing base_library.zip` step:

```
$ sudo ./macos-build.sh 
52 INFO: PyInstaller: 3.2.1
52 INFO: Python: 3.6.0
189 INFO: Platform: Darwin-15.6.0-x86_64-i386-64bit
220 INFO: UPX is not available.
221 INFO: Removing temporary files and cleaning cache in /Users/ac/Library/Application Support/pyinstaller
245 INFO: Extending PYTHONPATH with paths
['/Users/ac/got-your-back']
245 INFO: checking Analysis
245 INFO: Building Analysis because out00-Analysis.toc is non existent
245 INFO: Initializing module dependency graph...
272 INFO: Initializing module graph hooks...
338 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.2.1', 'console_scripts', 'pyinstaller')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 5, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 212, in __init__
    self.__postinit__()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 317, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/depend/analysis.py", line 560, in initialize_modgraph
    graph.import_hook(m)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/depend/analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2585, in _scan_code
    module, module_code_object, is_scanning_imports=False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2831, in _scan_bytecode
    global_attr_name = get_operation_arg_name()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2731, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range
```

This seems to be a [known issue](https://github.com/pyinstaller/pyinstaller/issues/2329) with PyInstaller not yet supporting Python 3.6, an item being tracked at [#2331](https://github.com/pyinstaller/pyinstaller/issues/2331).

Given that you explicitly upgraded the `macos-build.sh` script in commit [4686871](https://github.com/jay0lee/got-your-back/commit/468687188b1a51261e37cc622258a1ea8c38132a), I'm wondering if I'm missing a build step or dependency. I can confirm that reverting the build script and using Python 3.5 works.

**Comment by lele1122** [comment]
Hi, how can I use python 3.5 with PyInstaller if I have already installed python 3.6?

**Comment by adamci** [comment]
I didn't do anything fancy. I have multiple versions of Python installed on my machine, and on line 6 of the `macos-build.sh` script, I simply changed the version to point to 3.5:
```
/Library/Frameworks/Python.framework/Versions/3.5/bin/pyinstaller -F --clean --distpath=gyb macos-gyb.spec
```
Of course all this assumes that you've pip installed pyinstaller in your Python 3.5 context.

**Comment by jay0lee** [comment]
closing this out as pyinstaller now supports 3.7 :-)
