### ISSUE TITLE
GYB crashes while backing up

### ISSUE THREAD

**Issue by akatkim** [jay0lee/got-your-back#145]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. ./gyb --email <email address>@gmail.com --action backup
2.
3.

Expected outcome (what are you trying to do?):
Full back up of gmail

Actual outcome (what errors or bad behavior do you see instead?):
gyb crashed with following output to console

Traceback (most recent call last):
  File "http/client.py", line 541, in _get_chunk_left
  File "http/client.py", line 508, in _read_next_chunk_size
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "http/client.py", line 558, in _readall_chunked
  File "http/client.py", line 543, in _get_chunk_left
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gyb.py", line 1580, in <module>
  File "gyb.py", line 1044, in main
  File "gyb.py", line 487, in callGAPI
  File "oauth2client/util.py", line 137, in positional_wrapper
  File "googleapiclient/http.py", line 1397, in execute
  File "googleapiclient/http.py", line 1337, in _execute
  File "oauth2client/transport.py", line 169, in new_request
  File "httplib2/__init__.py", line 1314, in request
  File "httplib2/__init__.py", line 1064, in _request
  File "httplib2/__init__.py", line 1046, in _conn_request
  File "http/client.py", line 455, in read
  File "http/client.py", line 565, in _readall_chunked
http.client.IncompleteRead: IncompleteRead(83719663 bytes read)
Failed to execute script gyb

**Comment by b0ustiflex** [comment]
I have the same issue @akatkim. Were you able to resolve it ?
