### ISSUE TITLE
service-account - Failure to authenticate on Windows.

### ISSUE THREAD

**Issue by daniejstriata** [jay0lee/got-your-back#153]
I am successfully running GYB on Linux. I needed to do a restore from a Windows device. I copied client_secrets.json and oauth2service.json from my Linux device to the Windows device.

Note that the command I ran below uses a valid email address without the quotes.

Full steps to reproduce the issue:
1. Ran  "gyb.exe --email "email address" --action estimate" and completed the sign on for the account.
2. Gyb starting pulling the message numbers from Google. 
3. Proceeded to run with Service account and got the following error:

```
G:\GMail_archive\gyb>gyb.exe --email  "email address" --action estimate --service-account
Traceback (most recent call last):
  File "gyb.py", line 1580, in <module>
  File "gyb.py", line 969, in main
  File "gyb.py", line 439, in buildGAPIServiceObject
  File "oauth2client\service_account.py", line 221, in from_json_keyfile_name
  File "json\__init__.py", line 268, in load
  File "json\__init__.py", line 319, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 7 column 1 (char 1231)
Failed to execute script gyb
```

Expected outcome (what are you trying to do?):
I'm trying to connect to G-Suite using Gyb and a service account. The same service account file works on my linux PC
Actual outcome (what errors or bad behavior do you see instead?):
Gyb fails to run when using a service-account

**Comment by daniejstriata** [comment]
The .json file I used was corrupted. I missed to closing bracket due to no CRLF on Windows.
