### ISSUE TITLE
GYB on Synology NAS

### ISSUE THREAD

**Issue by subibro** [jay0lee/got-your-back#154]
I am trying to use GYB on Synology, downloaded the Linux source for v1.00, Synology has python3 installed, authorization goes through fine, it begins to work and issues:
Got 58613 Message IDs
GYB needs to examine 58613 messages
GYB already has a backup of 0 messages
GYB needs to backup 58613 messages
Traceback (most recent call last):
  File "gyb.py", line 1580, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 1044, in main
    callGAPI(gbatch, None, soft_errors=True)
  File "gyb.py", line 487, in callGAPI
    return method.execute()
  File "/volume1/NetBackup/hb/docs/gyb/got-your-back-1.0/got-your-back-1.0/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/volume1/NetBackup/hb/docs/gyb/got-your-back-1.0/got-your-back-1.0/googleapiclient/http.py", line 1397, in execute
    self._execute(http, self._order, self._requests)
  File "/volume1/NetBackup/hb/docs/gyb/got-your-back-1.0/got-your-back-1.0/googleapiclient/http.py", line 1337, in _execute
    headers=headers)
  File "/volume1/NetBackup/hb/docs/gyb/got-your-back-1.0/got-your-back-1.0/oauth2client/transport.py", line 169, in new_request
    redirections, connection_type)
  File "/volume1/NetBackup/hb/docs/gyb/got-your-back-1.0/got-your-back-1.0/httplib2/__init__.py", line 1314, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/volume1/NetBackup/hb/docs/gyb/got-your-back-1.0/got-your-back-1.0/httplib2/__init__.py", line 1064, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/volume1/NetBackup/hb/docs/gyb/got-your-back-1.0/got-your-back-1.0/httplib2/__init__.py", line 1017, in _conn_request
    response = conn.getresponse()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/http/client.py", line 243, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

Any insight?

**Comment by subibro** [comment]
The full report below:
Traceback (most recent call last):
  File "gyb.py", line 1580, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 1044, in main
    callGAPI(gbatch, None, soft_errors=True)
  File "gyb.py", line 487, in callGAPI
    return method.execute()
  File "/volume1/NetBackup/hb/docs/gyb/got-your-back-1.0/got-your-back-1.0/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/volume1/NetBackup/hb/docs/gyb/got-your-back-1.0/got-your-back-1.0/googleapiclient/http.py", line 1397, in execute
    self._execute(http, self._order, self._requests)
  File "/volume1/NetBackup/hb/docs/gyb/got-your-back-1.0/got-your-back-1.0/googleapiclient/http.py", line 1337, in _execute
    headers=headers)
  File "/volume1/NetBackup/hb/docs/gyb/got-your-back-1.0/got-your-back-1.0/oauth2client/transport.py", line 169, in new_request
    redirections, connection_type)
  File "/volume1/NetBackup/hb/docs/gyb/got-your-back-1.0/got-your-back-1.0/httplib2/__init__.py", line 1314, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/volume1/NetBackup/hb/docs/gyb/got-your-back-1.0/got-your-back-1.0/httplib2/__init__.py", line 1064, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/volume1/NetBackup/hb/docs/gyb/got-your-back-1.0/got-your-back-1.0/httplib2/__init__.py", line 1017, in _conn_request
    response = conn.getresponse()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/http/client.py", line 243, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by jay0lee** [comment]
This is an issue with your SSL/TLS connection to Google.
