### ISSUE TITLE
SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC

### ISSUE THREAD

**Issue by centic9** [jay0lee/got-your-back#156]
Full steps to reproduce the issue:
1. run GYB with action "backup"

This is on Ubuntu 16.04 Xenial with latest updates applied.

Expected outcome (what are you trying to do?):

backup succeeds

Actual outcome (what errors or bad behavior do you see instead?):

error message somehwere in SSL handling

Using backup folder GYB-GMail-Backup-xyz@gmail.com
Got 2000 Message IDs                                                           
GYB needs to examine 2000 messages
GYB already has a backup of 1300 messages
GYB needs to backup 700 messages
Traceback (most recent call last):
  File "gyb.py", line 1582, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 1046, in main
    callGAPI(gbatch, None, soft_errors=True)
  File "gyb.py", line 489, in callGAPI
    return method.execute()
  File "/usbb/Backup/gmail-backup/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usbb/Backup/gmail-backup/googleapiclient/http.py", line 1411, in execute
    self._execute(http, self._order, self._requests)
  File "/usbb/Backup/gmail-backup/googleapiclient/http.py", line 1343, in _execute
    headers=headers)
  File "/usbb/Backup/gmail-backup/oauth2client/transport.py", line 169, in new_request
    redirections, connection_type)
  File "/usbb/Backup/gmail-backup/httplib2/__init__.py", line 1322, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usbb/Backup/gmail-backup/httplib2/__init__.py", line 1072, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usbb/Backup/gmail-backup/httplib2/__init__.py", line 1054, in _conn_request
    content = response.read()
  File "/usr/lib/python3.5/http/client.py", line 455, in read
    return self._readall_chunked()
  File "/usr/lib/python3.5/http/client.py", line 558, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.5/http/client.py", line 541, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.5/http/client.py", line 501, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1977)

**Comment by centic9** [comment]
Googling a bit points at various different causes:
* Problem with OpenSSL in Ubuntu
* Multi-threading problem - https://stackoverflow.com/questions/3724900/python-ssl-problem-with-multiprocessing
* Something else: https://github.com/randomchars/pushbullet.py/issues/119 https://github.com/requests/requests/issues/1906 https://github.com/platformio/platformio-core/issues/645

Probably the following could help: https://lukasa.co.uk/2013/01/Choosing_SSL_Version_In_Requests/

**Comment by jay0lee** [comment]
This is an issue with security/antivirus/firewall on your PC or network, please check there.
