### ISSUE TITLE
Unable to restore mbox file

### ISSUE THREAD

**Issue by loweehahn** [jay0lee/got-your-back#160]
Hi!

I have an mbox file which is 40GB large. When trying to restore this is what I get:
```
Restoring from 40.94GB file c:\gyb\sarah.lim@example.com.mbox...
large files may take some time to open.
Traceback (most recent call last):
  File "gyb.py", line 1580, in <module>
  File "gyb.py", line 1252, in main
  File "mailbox.py", line 131, in items
  File "mailbox.py", line 124, in iteritems
  File "mailbox.py", line 72, in __getitem__
  File "mailbox.py", line 778, in get_message
  File "mailbox.py", line 1641, in __init__
  File "mailbox.py", line 1493, in __init__
  File "email\__init__.py", line 46, in message_from_bytes
  File "email\parser.py", line 124, in parsebytes
  File "email\parser.py", line 68, in parsestr
MemoryError
Failed to execute script gyb
```
If this is due to the huge size of the mbox file?

**Comment by jay0lee** [comment]
Due to limitations of the Python mbox implementation you are running out of memory loading the mbox file into RAM. Try splitting the mbox into smaller files with

--action split-mbox

**Comment by Adam0111** [comment]
Hey,
It would be very helpful to make a youtube video on how to restore a .mbox file (GoogleTakeOut file)
