### ISSUE TITLE
Problem backing up large accounts

### ISSUE THREAD

**Issue by rimeco** [jay0lee/got-your-back#182]
Using GYB 1.11 on windows 10 I'm having troubles to backup 2 accounts of a G Suite domain.
These 2 are both the biggest accounts in the list with 76K and 85K messages. All the others (smaller ones) complete without problems.

The command used:
D:\gyb_1.11\gyb.exe --email user@domain.com --service-account --local-folder "\\path\"

Outcome:
Got 84583 Message IDs
GYB needs to examine 84583 messages
GYB already has a backup of 84204 messages
GYB needs to backup 379 messages
Traceback (most recent call last):
  File "gyb.py", line 1875, in <module>
  File "gyb.py", line 1301, in main
  File "gyb.py", line 522, in callGAPI
  File "googleapiclient\_helpers.py", line 130, in positional_wrapper
  File "googleapiclient\http.py", line 1432, in execute
  File "googleapiclient\http.py", line 1364, in _execute
  File "oauth2client\transport.py", line 175, in new_request
  File "oauth2client\transport.py", line 282, in request
  File "httplib2\__init__.py", line 1511, in request
  File "httplib2\__init__.py", line 1261, in _request
  File "httplib2\__init__.py", line 1185, in _conn_request
  File "http\client.py", line 1239, in request
  File "http\client.py", line 1285, in _send_request
  File "http\client.py", line 1234, in endheaders
  File "http\client.py", line 1065, in _send_output
  File "http\client.py", line 986, in send
  File "ssl.py", line 972, in sendall
  File "ssl.py", line 941, in send
  File "ssl.py", line 642, in write
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
[4916] Failed to execute script gyb

What could I try to fix this?
Thanks in advance!

**Comment by jay0lee** [comment]
Does the same error get thrown every time you run the command?

**Comment by rimeco** [comment]
I tried at least 5 times since this morning, to rule out local connection problems.
So far I get the error every time, but only for those 2 accounts. Other accounts go fine in the meantime.

**Comment by tinyapps** [comment]
Had no issue downloading 67,100 emails (over 26GB) from a G Suite account for the first time using the macOS binary contained in [gyb-1.11-macos.tar.xz](https://github.com/jay0lee/got-your-back/releases/download/v1.11/gyb-1.11-macos.tar.xz):

```
$ gyb --email name@example.com --action backup

Using backup folder GYB-GMail-Backup-name@example.com
Got 67100 Message IDs                                                           
GYB needs to examine 67100 messages
GYB already has a backup of 0 messages
GYB needs to backup 67100 messages
backed up 67100 of 67100 messages                                               

GYB needs to refresh 0 messages
```

**Comment by jay0lee** [comment]
These are generally network errors.

- Don't backup over WiFi. It can be flaky
- Try turning Security/Antivirus software off, they can interfere with GYB connections.
- Ultimately GYB should be able to handle and recover from these issues as you found.
