### ISSUE TITLE
error while using the script

### ISSUE THREAD

**Issue by rahulkatarey** [jay0lee/got-your-back#2]
OS: windows 7
C:\gyb>gyb --email <myemail>@gmail.com --action estimate
Traceback (most recent call last):
  File "gyb.py", line 1317, in <module>
  File "gyb.py", line 572, in main
  File "gimaplib.pyo", line 47, in ImapConnect
  File "imaplib.pyo", line 1148, in __init__
  File "imaplib.pyo", line 163, in __init__
  File "imaplib.pyo", line 1159, in open
  File "socket.pyo", line 571, in create_connection
socket.error: [Errno 10060] A connection attempt failed because the connected pa
rty did not properly respond after a period of time, or established connection f
ailed because connected host has failed to respond

C:\gyb>gyb --email <myemail>@gmail.com --action backup
Traceback (most recent call last):
  File "gyb.py", line 1317, in <module>
  File "gyb.py", line 572, in main
  File "gimaplib.pyo", line 47, in ImapConnect
  File "imaplib.pyo", line 1148, in __init__
  File "imaplib.pyo", line 163, in __init__
  File "imaplib.pyo", line 1159, in open
  File "socket.pyo", line 571, in create_connection
socket.error: [Errno 10060] A connection attempt failed because the connected pa
rty did not properly respond after a period of time, or established connection f
ailed because connected host has failed to respond

**Comment by jay0lee** [comment]
IMAP versions are no longer supported. Please upgrade.
