### ISSUE TITLE
Fail to auth service scopes, with traceback

### ISSUE THREAD

**Issue by garyo** [jay0lee/got-your-back#220]
I'm getting repeated failures during service account authorization. 
```
Are you ready to authorize GYB to backup and restore G Suite user email? (yes or no) yes
Great! Checking service account scopes.This will fail the first time. Follow the steps to authorize and retry. It can take a few minutes for scopes to PASS after they've been authorized in the admin console.

 Scope: https://mail.google.com/                                     FAIL
 Scope: https://www.googleapis.com/auth/apps.groups.migration        FAIL
 Scope: https://www.googleapis.com/auth/drive.appdata                FAIL
 Scope: https://www.googleapis.com/auth/userinfo.email               FAIL
Traceback (most recent call last):
  File "gyb.py", line 2132, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 1480, in main
    doCheckServiceAccount()
  File "gyb.py", line 1071, in doCheckServiceAccount
    %s\n''' % (user_domain, credentials.client_id, ',\n'.join(all_scopes))
UnboundLocalError: local variable 'credentials' referenced before assignment
[8772] Failed to execute script gyb
Service account authorization failed. Confirm you entered the scopes correctly in the admin console. It can take a few minutes for scopes to PASS after they are entered in the admin console so if you're sure you entered them correctly, go grab a coffee and then hit Y to try again. Say N to skip admin authorization.
```
I know it's supposed to take a while, and I've retried the above for about 20 min now. The thing that concerns me is the `UnboundLocalError` python traceback -- is that expected?

I'm using latest GYB, headless on Linux. Google Cloud console looks OK, I can see the active service account. What should I try next?

**Comment by garyo** [comment]
It seems it was actually OK (it had actually created all the auth credentials it needs) -- once I Ctrl-C'ed out of that loop, I was able to use it with `~/bin/gyb/gyb --email me@example.com --action estimate` just fine, and am now transferring my emails!
