### ISSUE TITLE
Fails to restore from mbox

### ISSUE THREAD

**Issue by banchioa** [jay0lee/got-your-back#24]
HI,

I am trying to move my e-mail (from claws client) to gmail. I have exported an mbox from
claws and now want to import it to gmail. When I do this

  python ./gyb.py --email *****@gmail.com --action restore-mbox --local-folder inbox_claws --label-restored "F"

I get the following error message

     Using backup folder inbox_claws
     Traceback (most recent call last):
       File "./gyb.py", line 1323, in <module>
         main(sys.argv[1:])
       File "./gyb.py", line 601, in main
         sqlconn = sqlite3.connect(sqldbfile, detect_types=sqlite3.PARSE_DECLTYPES)
     sqlite3.OperationalError: unable to open database file

This is done from a Centos 6.0 server, but the same error was obtained also from
a Windows environment.

Any idea to solve this?

regards,

adolfo

**Comment by banchioa** [comment]
I found the problem:  the local folder I was passing did not exist (actually i was passing the inbox filename).
