### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes:

### ISSUE THREAD

**Issue by ismdcf** [jay0lee/got-your-back#259]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. Installed the app using bash <(curl -s -S -L https://git.io/gyb-install)
2. ran the setup got the following error when trying to do auto with permission default permission and pasted the verification code 
3.Got this error 

`Traceback (most recent call last):
  File "site-packages/googleapiclient/discovery.py", line 284, in _retrieve_discovery_doc
  File "json/__init__.py", line 357, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 186 column 4 (char 5208)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gyb.py", line 2190, in <module>
  File "gyb.py", line 1528, in main
  File "gyb.py", line 1231, in doesTokenMatchEmail
  File "gyb.py", line 523, in buildGAPIObject
  File "site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
  File "site-packages/googleapiclient/discovery.py", line 222, in build
  File "site-packages/googleapiclient/discovery.py", line 287, in _retrieve_discovery_doc
googleapiclient.errors.InvalidJsonError
`

Expected outcome (what are you trying to do?):

I was suppose to restore a .mbox file to the email account

Actual outcome (what errors or bad behavior do you see instead?):
`Traceback (most recent call last):
  File "site-packages/googleapiclient/discovery.py", line 284, in _retrieve_discovery_doc
  File "json/__init__.py", line 357, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 186 column 4 (char 5208)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gyb.py", line 2190, in <module>
  File "gyb.py", line 1528, in main
  File "gyb.py", line 1231, in doesTokenMatchEmail
  File "gyb.py", line 523, in buildGAPIObject
  File "site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
  File "site-packages/googleapiclient/discovery.py", line 222, in build
  File "site-packages/googleapiclient/discovery.py", line 287, in _retrieve_discovery_doc
googleapiclient.errors.InvalidJsonError
`

Version info from gyb --help 

Got Your Back 1.36
https://git.io/gyb
Jay Lee - jay0lee@gmail.com
Python 3.8.1 64-bit final
google-api-client 1.7.11
Linux-4.4.0-176-generic-x86_64-with-glibc2.4 x86_64
Path: /home/ismail/bin/gyb
OpenSSL 1.1.1d  10 Sep 2019
www.googleapis.com connects using TLSv1.3 TLS_AES_256_GCM_SHA384

Thanks for the awesome work (y)

**Comment by ismdcf** [comment]
The issue was I didn't have python3.8 installed on my PC 

` sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.8 `
