### ISSUE TITLE
Restore mbox failing

### ISSUE THREAD

**Issue by Toni3Ash** [jay0lee/got-your-back#269]
Hey. Sorry, I'm new to a lot of this, so if I did something that was obviously wrong please let me know. 

C:\gyb>gyb --email [redacted]@gmail.com --action restore-mbox

Using backup folder GYB-GMail-Backup-[redacted]@gmail.com

Restoring from 1.28gb file GYB-GMail-Backup-[redacted]@gmail.com\All mail Includin
g Spam and Trash.mbox...

Traceback (most recent call last):%
  File "gyb.py", line 2190, in <module>
  File "gyb.py", line 1945, in main
  File "gyb.py", line 574, in callGAPI
  File "site-packages\googleapiclient\_helpers.py", line 130, in positional_wrap
per
  File "site-packages\googleapiclient\http.py", line 1493, in execute
  File "gyb.py", line 1372, in restored_message
sqlite3.IntegrityError: datatype mismatch
[4788] Failed to execute script gyb

**Comment by jay0lee** [comment]
It looks like you are using a regular GYB backup folder to restore mbix files. Can you create an empty folder, place just the mbox files there and try again?

**Comment by Toni3Ash** [comment]
Okay. 

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd \gyb

C:\gyb>gyb --email [redacted]@gmail.com --action restore-mbox --local-folder "C:\U
sers\[redacted]\Documents\Takeout\Mail"

Using backup folder C:\Users\[redacted]\Documents\Takeout\Mail
Traceback (most recent call last):
  File "gyb.py", line 1125, in get_db_settings
sqlite3.OperationalError: no such table: settings

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gyb.py", line 2190, in <module>
  File "gyb.py", line 1559, in main
  File "gyb.py", line 1129, in get_db_settings
AttributeError: 'OperationalError' object has no attribute 'message'
[1228] Failed to execute script gyb

C:\gyb>
