### ISSUE TITLE
Traceback returns failed to execute script gyb

### ISSUE THREAD

**Issue by scidmail** [jay0lee/got-your-back#280]
I'm reinstalling gyb after reformatting my hard drive. I went through the steps and found the information to use desktop app instead of "other" and did that. I then entered the verification code I was provided when I hit return, this was the respoinse.

Traceback (most recent call last):
  File "gyb.py", line 2206, in <module>
  File "gyb.py", line 1546, in main
  File "gyb.py", line 525, in buildGAPIObject
  File "site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
  File "site-packages\googleapiclient\discovery.py", line 264, in build
  File "site-packages\googleapiclient\discovery.py", line 245, in build
  File "site-packages\googleapiclient\discovery.py", line 308, in _retrieve_discovery_doc
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest returned "The caller does not have permission">
[8356] Failed to execute script gyb

I cannot find anything with this exact error. Did I do something to cause this or is this a new issue?

Barb

**Comment by jay0lee** [comment]
There is currently an issue with Gmail API on Google's end. See:

https://issuetracker.google.com/issues/160441983

the issue breaks GYB but hopefully Google can fix it soon.

Jay Lee

**Comment by scidmail** [comment]
Thank you for the information. At least it's not just me.  :-)

**Comment by lifers5555** [comment]
Hmm, From Google:

> go...@google.com<go...@google.com> #118Jul 7, 2020 05:06PM
> Marked as fixed.
> Hi everyone!
> 
> This issue has been resolved.
> 
> If you run into this behaviour again, please open a new Issue with the necessary details.

And all the complaints in that threat cleared up. However I'm still having that issue on both Win and Mac when trying to restore MBox files.

**Comment by UnknownAlienTechnologies** [comment]
Hi, I still have this issue. 
Any update?

**Comment by mehyaa** [comment]
Similar error here:
```
Traceback (most recent call last):
  File "gyb.py", line 2206, in <module>
  File "gyb.py", line 1511, in main
  File "gyb.py", line 460, in doGYBCheckForUpdates
  File "httplib2\__init__.py", line 1985, in request
  File "httplib2\__init__.py", line 1650, in _request
  File "httplib2\__init__.py", line 1557, in _conn_request
  File "httplib2\__init__.py", line 1391, in connect
  File "httplib2\__init__.py", line 1324, in connect
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[20996] Failed to execute script gyb
```

Seems like the issue on Google side has been closed because of inactivity:
https://issuetracker.google.com/issues/160441983
