### ISSUE TITLE
Never mark spam on restore

### ISSUE THREAD

**Issue by aaronadamsCA** [jay0lee/got-your-back#342]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. Back up from one account
2. Restore to another account

Expected outcome (what are you trying to do?): All messages restored with similar structure.

Actual outcome (what errors or bad behavior do you see instead?): Thousands of legitimate messages from the first account classified as spam in the second account.

Unfortunately Gmail won't let me bulk mark them all "not spam", either, so this is a whole lot of repetitive clicking to rectify.

I see the Gmail API has a `neverMarkSpam` option on some endpoints, but I can't tell if it's available on the endpoint you're using because I can't read Python. 🙃

**Comment by jay0lee** [comment]
Yes, GYB sets this parameter:

https://github.com/jay0lee/got-your-back/blob/main/gyb.py#L1971

so this shouldn't be happening. Can you provide sample messages or a sample backup that is showing this problem?

**Comment by aaronadamsCA** [comment]
I'm up to several thousand messages in spam, but thankfully I found a workaround:

1. Search `label:spam -label:inbox`
2. Select all conversations that match this search
3. Move to inbox

**Comment by aaronadamsCA** [comment]
Each message in spam shows the same reason for being there:

> **Why is this message in spam?** It is similar to messages that were identified as spam in the past.

So it doesn't seem like it would be a phishing filter thing (my old and new addresses are similar, which had me wondering).

Here is a cleaned-up version of the commands I used:

```shell
cd
bash <(curl -s -S -L https://git.io/gyb-install)

mkdir first@firstlast.ca
cd first@firstlast.ca/
~/bin/gyb/gyb --email first@firstlast.ca --action quota
~/bin/gyb/gyb --email first@firstlast.ca --action backup

mkdir firstlast.ca@gmail.com
cd firstlast.ca@gmail.com/
~/bin/gyb/gyb --email firstlast.ca@gmail.com --action create-project
~/bin/gyb/gyb --email firstlast.ca@gmail.com --action restore --local-folder ../first@firstlast.ca/GYB-GMail-Backup-first@firstlast.ca/ --label-restored "firstlast.ca"
```

The messages going to spam are decidedly the "spammier" ones, it's almost exclusively newsletters and notification emails; so it does seem like the spam filter is somehow processing each inbound message despite being asked not to.

**Comment by aaronadamsCA** [comment]
> Can you provide sample messages or a sample backup that is showing this problem?

Let me know if any of the information above helps. If not, after my restore finishes running, I can try reproducing the problem with a small backup that I'd be comfortable sharing.

**Comment by bvinnerd** [comment]
I'm seeing this issue as well, backing up a Workspace account and restoring to a free Gmail account.

I have a total of 53,001 messages in the backup, and on restore there was ~7,200 messages in the Spam folder.

My workaround was to move all of those messages in Spam back to Inbox (by selecting, 100 messages at a time and clicking the Not Spam button in the Gmail UI).

If you're going to do this, please ensure that you have 0 spam messages in the target Gmail account, otherwise you could end up moving genuine spam into your Inbox.

**Comment by flipflophhj** [comment]
I have this issue too 15000 msgs in spam. Mainly very old messages.

Also many seem gotten the date set to the restore time instead of the original date it was sent.

**Comment by jay0lee** [comment]
I just released GYB 1.55 which adds a `--cleanup` option on restore. This tells GYB to confirm the message has a valid `From:`, `Message-ID:` and `Date:` header on it before restoring. This should prevent the message from landing in Spam.

Can a few people do some testing and confirm it works for them? See the 1.55 release details for more info:

git.io/gyb-releases

**Comment by flipflophhj** [comment]
Hm.. I though if I emptied that spam folder and then did a restore it would restore all those messages again but it doesn't seem so. 
What should I do ?

**Comment by jay0lee** [comment]
You need to tell GYB to try restoring all messages again with --noresume.

Jay

**Comment by flipflophhj** [comment]
Hm it would be nice to be able to label the messages that were cleaned up though. I tried to use label-restored but it labels everything now.

**Comment by flipflophhj** [comment]
Traceback (most recent call last):
  File "gyb.py", line 2532, in <module>
  File "gyb.py", line 2007, in main
  File "gyb.py", line 1769, in message_hygiene
  File "gyb.py", line 1713, in cleanup_from
  File "email\utils.py", line 215, in parseaddr
  File "email\_parseaddr.py", line 513, in __init__
  File "email\_parseaddr.py", line 256, in getaddrlist
TypeError: object of type 'Header' has no len()
[29748] Failed to execute script 'gyb' due to unhandled exception!

**Comment by flipflophhj** [comment]
Still got about 300 in spam of the 6000 restored before the exception

**Comment by jay0lee** [comment]
I can no longer reproduce the issue with the sample from the issue tracker and --cleanup. Can you share examples of messages that went to Spam?

**Comment by jay0lee** [comment]
I'd need to see the full headers as described at:

https://support.google.com/mail/answer/29436?hl=en

**Comment by jay0lee** [comment]
Yes, that's fine. You can post it here or email it to me.

**Comment by flipflophhj** [comment]
Ok I sent an email.

**Comment by flipflophhj** [comment]
Oh by the way I saw that all the mails that had the now() date after restore seems to have a correct date in msg-db.sqlite so maybe that could be used for --cleanup

**Comment by brechmos** [comment]
I am in the same boat (185,000 email to transfer though). I was watching my Spam as the transfer was happening and saw some go in and then automatically go out of Spam. I was nervous the "older than 30 days will be deleted" thing was happening faster than I was moving them out of Spam.

I am redoing my restore but put this filter in place:
![image](https://user-images.githubusercontent.com/887675/151886623-b1de6315-e273-424e-bd08-ba16df4aefeb.png)

I have not seen anything to to Spam. When the restore is done I'll turn off that filter.

I don't know enough about how quickly "older than 30 days" gets removed from Spam, and makes a data hoarder nervous.

**Comment by jay0lee** [comment]
Has anyone else tested with --cleanup to see if that helps?

**Comment by flipflophhj** [comment]
Did my EML files work fine for you?

man. 31. jan. 2022 23.59 skrev Jay Lee ***@***.***>:

> Has anyone else tested with --cleanup to see if that helps?
>

**Comment by jhult** [comment]
FWIW, I am also experiencing emails going into Spam (I have not yet tried `--cleanup`).

**Comment by Suncatcher** [comment]
> Has anyone else tested with --cleanup to see if that helps?

Yes I am. It doesn't work.

My numbers on restoration: 

- without `--cleanup`
 200+ messages in SPAM out of 1500

- with `--cleanup`
123 messages in SPAM out of 604

I was restoring different accounts so absolute numbers are different but you can easily calculate the percentage, it's nearly the same.

**Comment by chrishoage** [comment]
I have been doing an import moving 69k emails from a workspace account to a personal gmail account 

I have been running into this same issue. 

> The messages going to spam are decidedly the "spammier" ones, it's almost exclusively newsletters and notification emails; so it does seem like the spam filter is somehow processing each inbound message despite being asked not to.

This has been my experience as well. Lots of receipts, newsletters, etc. 

I put in the same filter @brechmos did and that has helped eliminate messages going to spam.
