### ISSUE TITLE
Issue performing a backup from the Google Apps Business and Education Admins

### ISSUE THREAD

**Issue by bripsch** [jay0lee/got-your-back#42]
Ok so I followed the directions in the wiki located [here](https://github.com/jay0lee/got-your-back/wiki#google-apps-business-and-education-admins-backup-restore-and-estimate-users-and-restore-to-groups) and got this error in the terminal:

Traceback (most recent call last):
  File "gyb.py", line 1323, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 575, in main
    imapconn = gimaplib.ImapConnect(generateXOAuthString(options.email, options.service_account), options.debug)
  File "gyb.py", line 261, in generateXOAuthString
    credentials = oauth2client.client.SignedJwtAssertionCredentials(service_account_name=service_account, private_key=key, scope=scope, user_agent=getGYBVersion(' / '), prn=email)
AttributeError: 'module' object has no attribute 'SignedJwtAssertionCredentials'

Any thoughts on this?  I have looked around a bit and don't know where to go from here.

Thanks
B

**Comment by bripsch** [comment]
Ok after trying like 30 different things, I figured out I needed to uninstall Python 2 and leave Python 3.. now we're rolling!
