### ISSUE TITLE
b64encode issue when using restore-mbox

### ISSUE THREAD

**Issue by lbenelli** [jay0lee/got-your-back#56]
Tried restoring a small mbox file generated by a vault export. 
works on 0.31, doesn't work on 0.41

Here the error on 0.41 

Using backup folder mbox

Restoring from mbox\email.mbox
 message 1 of 4
Traceback (most recent call last):
  File "<string>", line 1491, in <module>
  File "<string>", line 1220, in main
  File "C:\Python3\lib\base64.py", line 121, in urlsafe_b64encode
  File "C:\Python3\lib\base64.py", line 62, in b64encode
TypeError: 'str' does not support the buffer interface

PS: Thanks for the great tools!

**Comment by meksone** [comment]
Same error on similar file (mbox from a Vault export), on Windows 10 x64 and GYB 0.41

**Comment by jay0lee** [comment]
This should be fixed in current master (soon to be released as 0.45)
