### ISSUE TITLE
While Restoring

### ISSUE THREAD

**Issue by gregfest** [jay0lee/got-your-back#66]
Is there away around this?

restoring single large message (7/9995)
restored single large message (7/9995)
restoring single large message (8/9995)
restored single large message (8/9995)
restoring single large message (13/9995)
Traceback (most recent call last):
  File "<string>", line 1491, in <module>
  File "<string>", line 1081, in main
  File "<string>", line 470, in callGAPI
  File "C:\Users\jlee\Documents\GitHub\got-your-back\oauth2client\util.py", line
 137, in positional_wrapper
  File "C:\Users\jlee\Documents\GitHub\got-your-back\googleapiclient\http.py", l
ine 722, in execute
  File "C:\Users\jlee\Documents\GitHub\got-your-back\oauth2client\util.py", line
 137, in positional_wrapper
  File "C:\Users\jlee\Documents\GitHub\got-your-back\oauth2client\client.py", li
ne 551, in new_request
  File "C:\Users\jlee\Documents\GitHub\got-your-back\httplib2\__init__.py", line
 1313, in request
  File "C:\Users\jlee\Documents\GitHub\got-your-back\httplib2\__init__.py", line
 1063, in _request
  File "C:\Users\jlee\Documents\GitHub\got-your-back\httplib2\__init__.py", line
 988, in _conn_request
  File "C:\Python3\lib\http\client.py", line 1088, in request
  File "C:\Python3\lib\http\client.py", line 1125, in _send_request
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 2407-240
8: ordinal not in range(256)

**Comment by apendergrass** [comment]
This looks to me like Error restoring with <a href="https://github.com/jay0lee/got-your-back/issues/51">UnicodeEncodeError #51</a>

**Comment by jay0lee** [comment]
fixed in master (soon to be 0.44)
