### ISSUE TITLE
Encoding error while restoring (version 0.41 on Windows 7)

### ISSUE THREAD

**Issue by massimoscorletti** [jay0lee/got-your-back#67]
During restore of a large backup I have the following error

restoring single large message (123/107401)                                     Traceback (most recent call last):
  File "<string>", line 1491, in <module>
  File "<string>", line 1081, in main
  File "<string>", line 470, in callGAPI
  File "C:\Users\jlee\Documents\GitHub\got-your-back\oauth2client\util.py", line 137, in positional_wrapper
  File "C:\Users\jlee\Documents\GitHub\got-your-back\googleapiclient\http.py", line 722, in execute
  File "C:\Users\jlee\Documents\GitHub\got-your-back\oauth2client\util.py", line 137, in positional_wrapper
  File "C:\Users\jlee\Documents\GitHub\got-your-back\oauth2client\client.py", line 551, in new_request
  File "C:\Users\jlee\Documents\GitHub\got-your-back\httplib2\__init__.py", line 1313, in request
  File "C:\Users\jlee\Documents\GitHub\got-your-back\httplib2\__init__.py", line 1063, in _request
  File "C:\Users\jlee\Documents\GitHub\got-your-back\httplib2\__init__.py", line 988, in _conn_request
  File "C:\Python3\lib\http\client.py", line 1088, in request
  File "C:\Python3\lib\http\client.py", line 1125, in _send_request
UnicodeEncodeError: 'latin-1' codec can't encode character '\udce0' in position 3613: ordinal not in range(256)

I'm running version 0.41 on Windows 7.

There is a way to prevent or handle these errors?

**Comment by Northgate-GIT** [comment]
+1 here. Similar error:
>restoring single large message (1119/9959)
>Traceback (most recent call last):
>File "<string>", line 1491, in <module>
>File "<string>", line 1081, in main
>File "<string>", line 470, in callGAPI
>File "C:\Users\jlee\Documents\GitHub\got-your-back\oauth2client\util.py", line 137, in positional_wrapper
>File "C:\Users\jlee\Documents\GitHub\got-your-back\googleapiclient\http.py", line 722, in execute
>File "C:\Users\jlee\Documents\GitHub\got-your-back\oauth2client\util.py", line 137, in positional_wrapper
>File "C:\Users\jlee\Documents\GitHub\got-your-back\oauth2client\client.py", line 551, in new_request
>File "C:\Users\jlee\Documents\GitHub\got-your-back\httplib2\__init__.py", line 1313, in request
>File "C:\Users\jlee\Documents\GitHub\got-your-back\httplib2\__init__.py", line 1063, in _request
>File "C:\Users\jlee\Documents\GitHub\got-your-back\httplib2\__init__.py", line 988, in _conn_request
>File "C:\Python3\lib\http\client.py", line 1088, in request
>File "C:\Python3\lib\http\client.py", line 1125, in _send_request UnicodeEncodeError: 'latin-1' codec can't encode characters in position 4033-4034: ordinal not in range(256)

I was already using the "--fast-restore" option because of earlier "Invalid From Header" error (
https://github.com/jay0lee/got-your-back/issues/61 )

I am also running GYB v0.41 , Windows 7 (64bit)

**Comment by jay0lee** [comment]
This is fixed in master branch (soon to be 0.44)
