### ISSUE TITLE
Error while restoring messages

### ISSUE THREAD

**Issue by samsar777** [jay0lee/got-your-back#71]
Hi,

I am trying to restore my emails, but an error occured.

restoring single large message (4/9338)                                         Traceback (most recent call last):
  File "<string>", line 1491, in <module>
  File "<string>", line 1081, in main
  File "<string>", line 470, in callGAPI
  File "C:\Users\jlee\Documents\GitHub\got-your-back\oauth2client\util.py", line 137, in positional_wrapper
  File "C:\Users\jlee\Documents\GitHub\got-your-back\googleapiclient\http.py", line 722, in execute
  File "C:\Users\jlee\Documents\GitHub\got-your-back\oauth2client\util.py", line 137, in positional_wrapper
  File "C:\Users\jlee\Documents\GitHub\got-your-back\oauth2client\client.py", line 551, in new_request
  File "C:\Users\jlee\Documents\GitHub\got-your-back\httplib2\__init__.py", line 1313, in request
  File "C:\Users\jlee\Documents\GitHub\got-your-back\httplib2\__init__.py", line 1063, in _request
  File "C:\Users\jlee\Documents\GitHub\got-your-back\httplib2\__init__.py", line 988, in _conn_request
  File "C:\Python3\lib\http\client.py", line 1088, in request
  File "C:\Python3\lib\http\client.py", line 1125, in _send_request
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 3525-3526: ordinal not in range(256)

Regards,
S.

**Comment by samsar777** [comment]
Seems like this is the same case as "Error restoring with UnicodeEncodeError"  #51

**Comment by natanbr** [comment]
Same here! any suggestions?

**Comment by fmaiabatista** [comment]
I have this error too. :(

No recent updates on that?

**Comment by jay0lee** [comment]
This is fixed in master branch (soon to be released as 0.44).
