### ISSUE TITLE
JSON decoding error on first run of backup

### ISSUE THREAD

**Issue by jessejoe** [jay0lee/got-your-back#85]
Running the latest GYB:
```
$ gyb.py --version
Got Your Back 0.44
http://git.io/gyb
Jay Lee - jay0lee@gmail.com
Python 3.4.3 64-bit final
Linux-3.8.0-27-generic-x86_64-with-Ubuntu-14.04-trusty x86_64
```

Getting JSON decode errors when backing up on the first run:
```
$ /mnt/nas/Backups/email/got-your-back/gyb.py --email "me@mydomain.com" --service-account --action backup --local-folder /mnt/nas/Backups/email/

Using backup folder /mnt/nas/Backups/email/
Got 366363 Message IDs                                                          1
GYB needs to examine 366363 messages
GYB already has a backup of 0 messages
GYB needs to backup 366363 messages
backed up 96000 of 366363 messages                                              Traceback (most recent call last):
  File "/mnt/nas/Backups/email/got-your-back/gyb.py", line 476, in callGAPI
    error = json.loads(e.content.decode('utf-8'))
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/nas/Backups/email/got-your-back/gyb.py", line 1515, in <module>
    main(sys.argv[1:])
  File "/mnt/nas/Backups/email/got-your-back/gyb.py", line 989, in main
    callGAPI(gbatch, None)
  File "/mnt/nas/Backups/email/got-your-back/gyb.py", line 480, in callGAPI
    except (KeyError, json.decoder.JSONDecodeError):
AttributeError: 'module' object has no attribute 'JSONDecodeError'
```

**Comment by jay0lee** [comment]
Need to upgrade to Python 3.5+

**Comment by jessejoe** [comment]
Thanks @jay0lee, works now.

Finally getting back to this and re-running, GYB says I only have `138817` messages versus the `366363` it said I had in January. Any reason this would be the case? I don't delete mail.

**Comment by akaii78** [comment]
@jay0lee  same problem here when installing and my Python3 version is Python3.9 
I cannot install GYB with this problem..
