### ISSUE TITLE
IncompleteRead error

### ISSUE THREAD

**Issue by fxer** [jay0lee/got-your-back#92]
I've tried several times now but get an IncompleteRead error (with different 'bytes read' amounts each time) when trying to complete a backup for one account. Several other large accounts have backed up fine, not sure how to find the single message gyb is failing on however.

```
localuser@mac got-your-back-0.45$ gyb --email backupacct@domain.com

Using backup folder GYB-GMail-Backup-backupacct@domain.com
Got 44951 Message IDs                                                           
GYB needs to examine 44951 messages
GYB already has a backup of 42800 messages
GYB needs to backup 2151 messages
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 526, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 493, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 543, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 528, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gyb.py", line 1503, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 977, in main
    callGAPI(gbatch, None)
  File "gyb.py", line 461, in callGAPI
    return method.execute()
  File "/Users/localuser/gyb/got-your-back-0.45/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/localuser/gyb/got-your-back-0.45/googleapiclient/http.py", line 1325, in execute
    self._execute(http, self._order, self._requests)
  File "/Users/localuser/gyb/got-your-back-0.45/googleapiclient/http.py", line 1265, in _execute
    headers=headers)
  File "/Users/localuser/gyb/got-your-back-0.45/oauth2client/client.py", line 622, in new_request
    redirections, connection_type)
  File "/Users/localuser/gyb/got-your-back-0.45/httplib2/__init__.py", line 1314, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/localuser/gyb/got-your-back-0.45/httplib2/__init__.py", line 1064, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/localuser/gyb/got-your-back-0.45/httplib2/__init__.py", line 1046, in _conn_request
    content = response.read()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 440, in read
    return self._readall_chunked()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 550, in _readall_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(11097098 bytes read)

```

The next run of the same command errored out at:

 `http.client.IncompleteRead: IncompleteRead(61086058 bytes read)`

My best guess is there is a group of emails on the same day, about 8 emails at 20m each, maybe gyb is trying to download them in a group of 100 or something and it's just too big?

Update: I ran the command for the 7th time (literally, the first 6 failed as mentioned) and it looks like it downloaded all the messages and is continuing the backup. Maybe it managed to get all the data before some timeout kicked in this time? I stopped all other traffic on my inet connection to make sure gyb had the full pipe.

**Comment by jay0lee** [comment]
This error indicates you have some sort of firewall / proxy interfering with HTTP / HTTPS connections on your network (or it may be AV software running on your local machine). This is not a GYB-specific issue.

**Comment by drjasonharrison** [comment]
Is there a way to set proxy variables for GYB? I tried http_proxy, and https_proxy on OSX. Then I used Proxifier (www.proxifier.com) to create a rule for it.  The error I was getting was:
```Traceback (most recent call last):
  File "gyb.py", line 1580, in <module>
  File "gyb.py", line 964, in main
  File "gyb.py", line 307, in requestOAuthAccess
  File "oauth2client/util.py", line 137, in positional_wrapper
  File "oauth2client/tools.py", line 253, in run_flow
  File "oauth2client/util.py", line 137, in positional_wrapper
  File "oauth2client/client.py", line 2027, in step2_exchange
  File "httplib2/__init__.py", line 1314, in request
  File "httplib2/__init__.py", line 1064, in _request
  File "httplib2/__init__.py", line 987, in _conn_request
  File "http/client.py", line 1252, in connect
  File "http/client.py", line 849, in connect
  File "socket.py", line 711, in create_connection
  File "socket.py", line 702, in create_connection
OSError: [Errno 65] No route to host
Failed to execute script gyb```
