### ISSUE TITLE
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by rabeyer** [jay0lee/got-your-back#98]
I have installed version 0.45 and I am attempting to get the --service-account to work. I have successfully used the older GYB where --service-account required the service account email address as a parameter.

I have set up a new service account to use, as per the current instructions. I am receiving an ssl certificate verification error.

OS X 10.9.5 with Python 3.3.5 installed from the binary installer at python.org.
Command:   python3 ./gyb.py --email my-email@my-domain.com --service-account --action estimate

What have I missed in setting up the new version? Thanks.
_____________________________
Traceback (most recent call last):
  File "gyb.py", line 1503, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 902, in main
    gmail = buildGAPIServiceObject('gmail')
  File "gyb.py", line 435, in buildGAPIServiceObject
    return googleapiclient.discovery.build(api, version, http=http, cache_discovery=False)
  File "/Users/administrator/gyb/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/administrator/gyb/googleapiclient/discovery.py", line 203, in build
    cache)
  File "/Users/administrator/gyb/googleapiclient/discovery.py", line 249, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/Users/administrator/gyb/oauth2client/client.py", line 598, in new_request
    self._refresh(request_orig)
  File "/Users/administrator/gyb/oauth2client/client.py", line 864, in _refresh
    self._do_refresh_request(http_request)
  File "/Users/administrator/gyb/oauth2client/client.py", line 896, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "/Users/administrator/gyb/httplib2/__init__.py", line 1314, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/administrator/gyb/httplib2/__init__.py", line 1064, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/administrator/gyb/httplib2/__init__.py", line 987, in _conn_request
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/http/client.py", line 1206, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/ssl.py", line 246, in wrap_socket
    _context=self)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/ssl.py", line 350, in __init__
    raise x
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/ssl.py", line 346, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/ssl.py", line 553, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)

**Comment by jay0lee** [comment]
This error generally indicates that a device on your network or security / Antivirus software on your computer is intercepting GYB's TLS / SSL connections to Google servers. You should turn off this software or whitelist GYB.
